language: crystal
services:
  - docker
env:
  global:
    - PORT=3000
  matrix:
    - APP=http
    - APP=kemal
    - APP=orion
    - APP=orion-old
    - APP=orion-oak
install:
  - docker build -t benchmark ./benchmark
  - cd $APP && shards build --release --no-debug
before_script: ./$APP/bin/$APP &
script: docker run --env=PORT=$PORT --net=host benchmark localhost
