language: crystal
services:
  - docker
env:
  global:
    - PORT=3000
    - TEST_ROUTE=/repos/OWNER/REPO/hooks/ID
  matrix:
    - APP=http
    - APP=kemal
    - APP=orion
    - APP=orion-old
    - APP=orion-oak
install:
  - docker build -t benchmark ./benchmark
  - cd $APP && shards build --release --no-debug
before_script: ./$APP/bin/$APP &
script:
  - curl http://localhost:${PORT}${TEST_ROUTE}
  - docker run --env=PORT=$PORT --net=host benchmark localhost
