version: '3'
services:
  benchmark-base: &benchmark
    build:
      context: ./benchmark
    volumes:
      - ./:/hostmachine
    environment:
      OUT_FILE: /hostmachine/results.txt
      PORT: 3000
      TEST_ROUTE: /repos/OWNER/REPO/hooks/ID
    command: kemal
  benchmark-kemal:
    <<: *benchmark
    links:
      - kemal
    command: kemal
  kemal:
    build:
      context: ./kemal
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-orion:
    <<: *benchmark
    links:
      - orion
    command: orion
  orion:
    build:
      context: ./orion
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-orion-old:
    <<: *benchmark
    links:
      - orion-old
    command: orion-old
  orion-old:
    build:
      context: ./orion-old
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-http:
    <<: *benchmark
    links:
      - http
    command: http
  http:
    build:
      context: ./http
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-sinatra:
    <<: *benchmark
    links:
      - sinatra
    command: sinatra
  sinatra:
    build:
      context: ./sinatra
    environment:
      PORT: 3000
    expose:
      - 3000
